add init container

diff --git a/kubernetes/apps/sgc/home/home-assistant/helmrelease.yaml b/kubernetes/apps/sgc/home/home-assistant/helmrelease.yaml
--- a/kubernetes/apps/sgc/home/home-assistant/helmrelease.yaml
+++ b/kubernetes/apps/sgc/home/home-assistant/helmrelease.yaml
@@ -42,6 +42,32 @@ spec:
         pod:
           restartPolicy: Always
           terminationGracePeriodSeconds: 30
+        initContainers:
+          fix-permissions:
+            image:
+              repository: alpine
+              tag: 3.20.3
+              pullPolicy: IfNotPresent
+            command:
+              - sh
+              - -c
+              - |
+                echo "Resetting permissions on /config to 0777";
+                if [ -d /config ]; then
+                  chmod -R 0777 /config || true
+                else
+                  echo "/config not found";
+                fi
+            securityContext:
+              runAsUser: 0
+              runAsGroup: 0
+              runAsNonRoot: false
+            resources:
+              requests:
+                cpu: 10m
+                memory: 16Mi
+              limits:
+                memory: 64Mi
         containers:
           app:
             image:
